### ISSUE TITLE
Mobile version bugs

### ISSUE THREAD

**Issue by athossampayo** [REBECANONATO/REBECANONATO#3]
Hey! I was checking your website as onde cool reference for react development and tried its mobile version. Seems to need to adapt the “Realizações” page from 4 to 3 columns:
![EF8CF2F4-8DEA-4FBC-8549-4D9AFF0E76E6](https://user-images.githubusercontent.com/67998510/89700803-ad142b00-d907-11ea-8801-4b53867abf0e.png)

 Also, I would adapt the Skills page to show at least 2 icons in the same line: 

![5BB156CB-F926-483E-B829-57F0FEF50EA6](https://user-images.githubusercontent.com/67998510/89700808-ba311a00-d907-11ea-83a1-d52937cd6969.png)

Also, I would check the “ Mais sobre mim:” page too, seems to have some problema with centralized text, but it might be effect of the error above. 

Also, you might wanna try some left and right aligned texts to check if they get a “cleaner aspect”, but thats just some random design opinions and not a bug. 

I used an iPhone X to check, so you can try its screen width when configuring. 

But its a really nice project! Really liked the end result, congrats!

**Comment by athossampayo** [comment]
The “ Mais sobre mim:” bug I said:
![927AC789-96A9-4B19-8ADA-0CBD5D22E47C](https://user-images.githubusercontent.com/67998510/89700894-99b58f80-d908-11ea-99a3-c81f4476f9c1.png)

**Comment by REBECANONATO** [comment]
I haven't really done the adaptation for the mobile version yet. I need to revise my css to work.

**Comment by REBECANONATO** [comment]
#hacktoberfest
